import os
import glob
import argparse
import subprocess
import shutil

def main():
    parser = argparse.ArgumentParser(description="Denoise a single WAV file or a batch of WAV files using the historical denoiser.")
    parser.add_argument("input_path", help="Path to a single WAV file or a directory containing WAV files to denoise.")
    args = parser.parse_args()

    input_path = os.path.abspath(args.input_path)
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Point to the existing inference.py script
    inference_script = os.path.join(base_dir, "denoiser", "inference.py")

    # Create the result directory
    result_dir = os.path.join(base_dir, "result")
    os.makedirs(result_dir, exist_ok=True)

    if not os.path.exists(inference_script):
        print(f"Error: Could not find the inference script at {inference_script}")
        return

    wav_files = []
    
    # Check if the user provided a single file or a directory
    if os.path.isfile(input_path):
        if input_path.lower().endswith(".wav"):
            wav_files.append(input_path)
        else:
            print(f"Error: The provided file is not a .wav file: {input_path}")
            return
    elif os.path.isdir(input_path):
        # Find all .wav files in the directory (recursively)
        wav_files = glob.glob(os.path.join(input_path, "**", "*.wav"), recursive=True)
    else:
        print(f"Error: The path {input_path} does not exist.")
        return
    
    # Filter out files that were already generated by previous runs 
    # (inference.py adds these suffixes to the outputs)
    ignore_suffixes = ["_denoised.wav", "_residual.wav", "_noisy_input.wav"]
    wav_files = [f for f in wav_files if not any(f.endswith(suffix) for suffix in ignore_suffixes)]
    
    # Prevent processing files that are already inside the result directory
    wav_files = [f for f in wav_files if not f.startswith(result_dir)]

    print(f"Found {len(wav_files)} WAV file(s) to process.")

    for wav_file in wav_files:
        print(f"\n--- Processing: {wav_file} ---")
        
        # Using Hydra override syntax: inference.audio="path/to/file.wav"
        cmd = [
            "python",
            inference_script,
            f"inference.audio={wav_file}"
        ]
        
        try:
            subprocess.run(cmd, check=True)
            
            # Move the generated files to the result directory
            base_path = os.path.splitext(wav_file)[0]
            filename_base = os.path.basename(base_path)
            
            for suffix in ignore_suffixes:
                generated_file = base_path + suffix
                if os.path.exists(generated_file):
                    shutil.move(generated_file, os.path.join(result_dir, filename_base + suffix))
        except subprocess.CalledProcessError as e:
            print(f"Failed to process {wav_file}. Error: {e}")

if __name__ == "__main__":
    main()